config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja/ do
    root "static_pages#home"
    get 'static_pages/help', as: "help"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    get "/courses", to: "courses#new"

    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :account_activations, only: :edit
    resources :registers
    resources :courses
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest

  has_many :registers
  has_many :courses, through: :registers, dependent: :destroy

  has_secure_password

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

class << self
    def new_token
      SecureRandom.urlsafe_base64
    end

  # Returns the hash digest of the given string.
    def User.digest string
      cost = if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
       BCrypt::Engine.cost
      end
        BCrypt::Password.create string, cost: cost
    end
  end

  def remember
    remember_token = new_token
    self.update_attributes(:remember_digest, digest(remember_token))
  end

  def authenticated? (attribute, token)
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update_attribute :remember_digest, nil
  end

  def activate
    update_columns activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  def downcase_email
    self.email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find_by(id: params[:id])
    @register = Register.new
    @ids = current_user.course_ids

    unless @user
      flash[:danger] = t(:user_not_found)
      redirect_to home_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t(:check)
      redirect_to root_url
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
  user = User.find_by(id: params[:id])
  if user&.destroy
    flash[:success] = t(:User_deleted)
  else
    flash[:danger] = t(:Delete_fail)
  end
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end

  def correct_user
    @user = User.find_by(id: params[:id])
    return if current_user?(@user)
    flash[:danger] = t("not_authorized")
    redirect_to(home_url)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80 }
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/users/_form.html.erb
<%= form_with model: course do |form| %>

  <div class="control-group">
    <p><%= form.label t("name"), class: 'control-label' %></p>
    <div class="controls">
      <div>
        <p><%= form.text_field :name %></p>
        <% course.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <div>
        <p><%= form.label t("description"), class: 'control-label' %></p>
        <p><%= form.text_area :description %></p>
        <% course.errors.full_messages_for(:description).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="control-group">
    <%= form.label t("status"), class: 'control-label' %>
    <div class="controls">
      <p><%= form.select :status, Course.statuses.keys.to_a %></p>
    </div>
  </div>

  <div class="control-group">
    <%= form.label t("duration"), class: 'control-label' %>
    <div class="controls">
      <p><%= form.select :total_month, ['3', '6', '12'] %></p>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <div>
        <p><%= form.submit %></p>
      </div>
    </div>
  </div>
<% end %>

<%= link_to t("cancel"), courses_path %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to t(:delete), user, method: :delete, data: {confirm: t(:sure)} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, t(:Edit_user)) %>
<% provide(:button_text, t(:Save_changes)) %>
<h1><% t (:Update_your_profile) %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
  <h1>All users</h1>

  <%= will_paginate %>

  <ul class="users">
    <%= render @users %>
  </ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t(:sign_up) %>
<% provide(:button_text, t(:create_my_account))%>
<h1><%= t(:sign_up) %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            <%= t (:the_form_contains)%>
            <%= pluralize @user.errors.count, t(:error) %>.
          </div>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.label :name, t(:name) %>
      <%= f.text_field :name %>
      <%= f.label :email, t(:email) %>
      <%= f.email_field :email %>
      <%= f.label :password, t(:password) %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, t(:confirmation) %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit t(:create_my_account), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>

<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
  </div>

  <div>
    <p>
      <% if current_user? @user %>
        <b><%= t("register_course") %>: </b>
        <%= form_for @register do |f| %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.collection_select :course_id, Course.where.not(id: @ids), :id, :name, prompt: "Select subject..." %>
          <%= f.submit t("register"), class: "btn btn-primary"%>
        <% end %>
      <% end %>
    </p>
  </div>

  <div class='card'>
    <b><%= t("course_enrolled") %>: </b><br>
    <div class="media">
      <div class="media-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th><%= t("date") %></th>
              <th><%= t("course") %></th>
              <th><%= t("status") %></th>
              <% if current_user? @user %>
                <th><%= t("action") %></th>
              <% end %>
            </tr>
          </thead>

          <tbody>
            <% @user.registers.each do |register| %>
              <tr>
                <td><%= register.updated_at.to_date %></td>
                <td><%= link_to register.course.name, register.course %></td>
                <td><%= register.status %></td>

                <td>
                  <% if current_user? @user %>
                    <%= button_to t("delete"), register_path(register),
                          method: :delete,
                          data: { confirm: t("are_you_sure") } %>
                        <%= form_for register do |f| %>
                          <%= f.hidden_field :status, :value => 'Approved' %>
                          <%= f.submit "Approve", data: {confirm: "sure"} %><br>
                        <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>