config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja/ do
    root "static_pages#home"
    get 'static_pages/help', as: "help"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    get "/courses", to: "courses#new"

    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :account_activations, only: :edit
    resources :registers
    resources :courses
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :logged_in_user

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find_by(id: params[:id])
    @register = Register.new
    @ids = @course.user_ids
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      flash[:success] = "Course created!"
      redirect_to @course
    else
      flash[:danger] = "Course create failed"
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])

    if @course.status == "Started"
      @course.started_at = Time.zone.now
    end

    if @course.update(course_params)
      flash[:success] = "Course updated"
      redirect_to @course
    else
      flash[:success] = "Course update failed"
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])

    if @course.status == "Opening"
      @course.destroy
      flash[:success] = "Course deleted"
      redirect_to courses_path
    else
      flash[:danger] = "Course in progress/finished"
      redirect_to courses_path
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :status, :total_month, :started_at)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<%= provide :title, t("edit_course") %>

<h1><%= t("edit_course") %></h1>

<%= render "form", course: @course %>

app/views/courses/index.html.erb
<%= provide :title, t("list_course") %>

<div class="col-md-6 col-md-offset-3"">
  <div class="row">
    <h1><%= t("list_course") %></h1>
    <div>
      <% if current_user %>
        <p><%= link_to t("new_course") , new_course_path %></p>
      <% end %>
    </div>
  </div>

  <div class="media text-justify">
    <div class="media-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th><%= t("date_updated") %></th>
            <th><%= t("course_id") %></th>
            <th><%= t("course") %></th>
            <th><%= t("status") %></th>
            <th><%= t("duration") %></th>
            <th><%= t("members") %></th>
            <th><%= t("detail") %></th>
            <% if current_user %>
              <th><%= t("action") %></th>
              <th><%= t("remove") %></th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <% @courses.each do |course| %>
            <tr>
              <td><%= course.updated_at.to_date %></td>
              <td><%= course.id %></td>
              <td><%= course.name %></td>
              <td><%= course.status %></td>
              <td><%= course.total_month %> <%= t("months") %></td>
              <td><%= course.registers.count %> <%= t("members") %></td>
              <td><%= link_to t("show"), course, class: "btn btn-mini" %></td>
              <% if current_user.admin? %>
                <td>
                  <%= link_to t("edit"), edit_course_path(course), class: "btn btn-mini" %>
                </td>
                <td><%= button_to t("delete"), course, method: :delete, data: { confirm: t("are_you_sure") }, class: "btn btn-mini" %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<%= provide :title, "course_registration" %>

<% if current_user.admin %>
  <h1>Add course</h1>
  <html>
    <body>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with model: @course do |f| %>
            <%= f.label :name, "Course name" %>
            <%= f.text_field :name, class: "form-control" %>
            <%= f.label :description, "Course description" %>
            <%= f.text_field :description, class: "form-control" %>
            <%= f.label :total_month, "Course total month" %>
            <%= f.number_field :total_month, class: "form-control" %>
            <%= f.label :status, "Course status" %>
            <%= f.select :status, ["Opening", "Started","Finished"] %>
            <%= f.submit "Create course", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </body>
  </html>
<% else %>
  <h3>Not admin</h3>
<% end %>

app/views/courses/show.html.erb
<% provide :title, @course.name %>

<div class="col-md-6 col-md-offset-3">
  <div>
    <h1><%= @course.name %></h1>
    <p><%= t("description") %>: <%= @course.description %></p>
    <p><%= t("status") %>: <%= @course.status %></p>
    <p><%= t("duration") %>: <%= @course.total_month %> <%= t("months") %></p>
    <p><%= t("total_member") %>: <%= @course.registers.count %> <%= t("members") %></p>

    <% if current_user.admin? %>
      <ul>
        <li><%= link_to t("edit"), edit_course_path(@course) %></li>
        <li><%= link_to t("delete"), course_path(@course),
                      method: :delete,
                      data: { confirm: t("are_you_sure") } %></li>
      </ul>
    <% end %>
    <p><%= link_to t("back_to_course"), courses_path, class: "btn btn-mini" %></p>
  </div>

  <div>
    <%= render 'registers/course_register' %>
  </div>

  <div>
    <% if current_user.admin? && !current_user?(@user) %>
      <b><%= t(".add_to_course") %>: </b>
      <%= form_for @register  do |f| %>
        <%= f.hidden_field :course_id, :value => @course.id %>
        <%= f.collection_select :user_id, User.where.not(id: @ids), :id, :name, prompt: "Select user..." %>
        <%= f.submit t("register_course"), class: "btn btn-primary"%>
      <% end %>
    <% end %>
  </div>

  <div>
    <br><b><%= t(".enrolled_student") %></b><br>
    <div class="media text-justify">
      <div class="media-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th><%= t("date") %></th>
              <th><%= t("name") %></th>
              <th><%= t("status") %></th>
              <% if current_user.admin? && !current_user?(@user) %>
                <th><%= t("action") %></th>
                <th><%= t("remove") %></th>
              <% end %>
            </tr>
          </thead>

          <tbody>
            <% @course.registers.each do |register| %>
              <tr>
                <td><%= register.updated_at.to_date %></td>
                <td><%= link_to register.user.name, register.user %></td>
                <td><%= register.status %></td>
                <% if current_user.admin? && !current_user?(@user) %>
                  <td>
                    <%= link_to t("review"), edit_register_path(register) %>
                  </td>
                  <td><%= button_to t("delete"), register_path(register),
                            method: :delete,
                            data: { confirm: t("are_you_sure") } %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>